/// Filename or SONAME fragment -> upstream project. Ordered: first match wins, so put
/// narrow patterns before broad ones.
pub const FILENAME: &[(&str, &str)] = &[
	(r"^libcrypto\.so|^libssl\.so", "openssl"),
	(r"^libcurl\.(so|a)", "curl"),
	(r"^libz\.so", "zlib"),
	(r"samba4|^libsmb|^libndr|^libdcerpc|^libsamba|^libsamdb|^libnetapi|^libwbclient|^libsmbconf|^libsecrets", "samba"),
	(r"^libkrb5|^libhx509|^libasn1-|^libroken|^libheimbase|^libhcrypto|^libgssapi|^libwind|^libcom_err", "heimdal"),
	(r"^libtalloc\.so", "talloc"),
	(r"^libtdb\.so", "tdb"),
	(r"^libtevent\.so", "tevent"),
	(r"^libldb\.so", "ldb"),
	(r"^libiptc|^libip4tc|^libip6tc|^libxtables", "iptables"),
	(r"^libipset", "ipset"),
	(r"^libmnl\.so", "libmnl"),
	(r"^libupnp\.so|^libixml\.so", "libupnp"),
	(r"^libpopt", "popt"),
	(r"^libstdc\+\+\.so|^libgcc_s\.so|^libssp\.so", "gcc-runtime"),
	(r"^libvolume_id\.so", "udev"),
	(r"^libexpat\.so", "expat"),
	(r"^libpcap\.so", "libpcap"),
	(r"^libnl(-\d)?\.so", "libnl"),
	(r"^libjson-c\.so", "json-c"),
	(r"^libjansson\.so", "jansson"),
	(r"^libavahi-", "avahi"),
	(r"^libssh2\.so", "libssh2"),
	(r"^libssh\.so", "libssh"),
	(r"^libsqlite3\.so", "sqlite"),
	(r"^libxml2\.so", "libxml2"),
	(r"^libmbedtls|^libmbedcrypto|^libmbedx509", "mbedtls"),
	(r"^libbz2\.so", "bzip2"),
	(r"^liblzma\.so", "xz"),
	(r"^libncurses|^libtinfo", "ncurses"),
	(r"^libpcre", "pcre"),
	(r"^libpng", "libpng"),
	(r"^libjpeg|^libturbojpeg", "libjpeg-turbo"),
	(r"^libfreetype", "freetype"),
	(r"^libnghttp2", "nghttp2"),
	(r"^libav(codec|format|util|filter|device|resample)|^libsw(scale|resample)", "ffmpeg"),
	(r"^ld-uClibc|^libdl\.so\.0|^libm\.so\.0|^libpthread\.so\.0|^libnsl\.so\.0|^libresolv\.so\.0|^libcrypt\.so\.0|^librt\.so\.0|^libutil\.so\.0", "uclibc"),
];

/// Basename -> project, for standalone executables.
pub const BINARY: &[(&str, &str)] = &[
	("busybox", "busybox"),
	("tcpdump", "tcpdump"),
	("pppd", "pppd"),
	("bzip2", "bzip2"),
	("lzop", "lzop"),
	("hdparm", "hdparm"),
	("lsof", "lsof"),
	("ntpclient", "ntpclient"),
	("pptpd", "pptpd"),
	("pptpctrl", "pptpd"),
	("dnsmasq", "dnsmasq"),
	("dropbear", "dropbear"),
	("openssl", "openssl"),
	("curl", "curl"),
	("wget", "wget"),
	("hostapd", "hostapd"),
	("wpa_supplicant", "wpa_supplicant"),
	("wpad", "wpa_supplicant"),
	("lighttpd", "lighttpd"),
	("uhttpd", "uhttpd"),
	("smbd", "samba"),
	("nmbd", "samba"),
	("php", "php"),
	("php-cli", "php"),
	("php-cgi", "php"),
	("perl", "perl"),
	("python", "python"),
	("lua", "lua"),
	("vsftpd", "vsftpd"),
	("proftpd", "proftpd"),
	("minidlna", "minidlna"),
	("openssh", "openssh"),
	("sshd", "openssh"),
];

/// Project -> version-extraction patterns, applied to file bytes. Capture group 1 is the
/// version. Only patterns anchored to a project-identifying token belong here; a bare
/// version regex matches noise.
pub const VERSION: &[(&str, &[&str])] = &[
	("openssl", &[r"OpenSSL (\d+\.\d+\.\d+[a-z]?)"]),
	("curl", &[r"libcurl/(\d+\.\d+\.\d+)", r"curl (\d+\.\d+\.\d+)"]),
	("busybox", &[r"BusyBox v(\d+\.\d+\.\d+)"]),
	("samba", &[r"samba-(\d+\.\d+\.\d+)", r"Version (\d+\.\d+\.\d+)"]),
	("uclibc", &[r"uClibc(?:-ng)?[- ](\d+\.\d+\.\d+)"]),
	("musl", &[r"musl libc.{0,40}?Version (\d+\.\d+\.\d+)"]),
	("libupnp", &[r"Portable SDK for UPnP devices/?(\d+\.\d+\.\d+)", r"libupnp/(\d+\.\d+\.\d+)"]),
	("iptables", &[r"iptables (\d+\.\d+\.\d+)"]),
	("tcpdump", &[r"tcpdump version (\d+\.\d+\.?\d*)"]),
	("libpcap", &[r"libpcap version (\d+\.\d+\.?\d*)"]),
	("mbedtls", &[r"mbed ?TLS (\d+\.\d+\.\d+)"]),
	("dnsmasq", &[r"dnsmasq-(\d+\.\d+)"]),
	("dropbear", &[r"dropbear[_ ](\d{4}\.\d+)"]),
	("expat", &[r"expat_(\d+\.\d+\.\d+)"]),
	("wpa_supplicant", &[r"wpa_supplicant v(\d+\.\d+)"]),
	("hostapd", &[r"hostapd v(\d+\.\d+)"]),
	("php", &[r"X-Powered-By: PHP/(\d+\.\d+\.\d+)", r"PHP/(\d+\.\d+\.\d+)"]),
	("lighttpd", &[r"lighttpd/(\d+\.\d+\.\d+)"]),
	("libssh", &[r"libssh-(\d+\.\d+\.\d+)"]),
	("proftpd", &[r"ProFTPD (\d+\.\d+\.\d+[a-z]?)"]),
	("openssh", &[r"OpenSSH_(\d+\.\d+)"]),
	("zlib", &[r"(?:in|de)flate (\d+\.\d+\.\d+) Copyright"]),
	("libpng", &[r"libpng version (\d+\.\d+\.\d+)"]),
	("bzip2", &[r"bzip2-(\d+\.\d+\.\d+)"]),
	("ffmpeg", &[r"FFmpeg version (\d+\.\d+(?:\.\d+)?)"]),
	("minidlna", &[r"MiniDLNA/(\d+\.\d+\.\d+)"]),
];

/// Projects whose SONAME encodes the RELEASE version rather than an ABI number.
/// This is per-project knowledge: applying it blindly invents versions. Adding avahi or
/// jansson here produced "avahi 5.3" and "jansson 11.1", both impossible.
pub const SONAME_RELEASE: &[(&str, &str)] = &[
	("zlib", r"^libz\.so\.(\d+\.\d+\.\d+)$"),
	("mbedtls", r"^libmbed(?:tls|crypto|x509)\.so\.(\d+\.\d+\.\d+)$"),
];

pub const FILENAME_VERSION: &[(&str, &str)] = &[
	("uclibc", r"^ld-uClibc-(\d+\.\d+\.\d+)\.so"),
	("musl", r"^ld-musl-[a-z0-9_]+-(\d+\.\d+\.\d+)"),
];

/// NVD files the same project under several vendor:product pairs. Emitting only one loses
/// findings: curl as haxx:libcurl alone dropped 46 CVEs filed under haxx:curl.
pub const CPE: &[(&str, &[&str])] = &[
	("openssl", &["openssl:openssl"]),
	("curl", &["haxx:curl", "haxx:libcurl", "curl:curl"]),
	("zlib", &["gnu:zlib", "zlib:zlib", "madler:zlib"]),
	("busybox", &["busybox:busybox"]),
	("musl", &["musl-libc:musl", "musl_project:musl"]),
	("uclibc", &["uclibc:uclibc", "uclibc-ng:uclibc-ng"]),
	("samba", &["samba:samba"]),
	("heimdal", &["heimdal_project:heimdal"]),
	("talloc", &["samba:talloc"]),
	("tdb", &["samba:tdb"]),
	("tevent", &["samba:tevent"]),
	("ldb", &["samba:ldb"]),
	("libupnp", &["libupnp_project:libupnp", "pupnp_project:pupnp"]),
	("mbedtls", &["arm:mbed_tls", "arm:mbedtls", "trustedfirmware:mbed_tls"]),
	("dnsmasq", &["thekelleys:dnsmasq"]),
	("wpa_supplicant", &["w1.fi:wpa_supplicant"]),
	("hostapd", &["w1.fi:hostapd"]),
	("libssh", &["libssh:libssh"]),
	("libssh2", &["libssh2:libssh2"]),
	("libpcap", &["tcpdump:libpcap"]),
	("tcpdump", &["tcpdump:tcpdump"]),
	("proftpd", &["proftpd:proftpd"]),
	("iptables", &["netfilter:iptables"]),
	("ipset", &["netfilter:ipset"]),
	("libmnl", &["netfilter:libmnl"]),
	("bzip2", &["bzip:bzip2", "bzip2_project:bzip2"]),
	("expat", &["libexpat_project:libexpat"]),
	("jansson", &["jansson_project:jansson", "digip:jansson"]),
	("avahi", &["avahi:avahi"]),
	("json-c", &["json-c:json-c"]),
	("sqlite", &["sqlite:sqlite"]),
	("libxml2", &["xmlsoft:libxml2"]),
	("pcre", &["pcre:pcre"]),
	("ncurses", &["gnu:ncurses"]),
	("dropbear", &["dropbear_ssh_project:dropbear_ssh"]),
	("pppd", &["point-to-point_protocol_project:point-to-point_protocol"]),
	("wget", &["gnu:wget"]),
	("xz", &["tukaani:xz"]),
	("php", &["php:php"]),
	("perl", &["perl:perl"]),
	("python", &["python:python"]),
	("lighttpd", &["lighttpd:lighttpd"]),
	("libpng", &["libpng:libpng"]),
	("libjpeg-turbo", &["libjpeg-turbo:libjpeg-turbo"]),
	("freetype", &["freetype:freetype"]),
	("nghttp2", &["nghttp2:nghttp2"]),
	("ffmpeg", &["ffmpeg:ffmpeg"]),
	("openssh", &["openbsd:openssh"]),
	("minidlna", &["minidlna_project:minidlna"]),
	("vsftpd", &["beasts:vsftpd"]),
	("popt", &["popt_project:popt"]),
	("udev", &["kernel:udev"]),
	("gcc-runtime", &["gnu:gcc"]),
	("lua", &["lua:lua"]),
	("uhttpd", &["openwrt:uhttpd"]),
	("libnl", &["infradead:libnl"]),
	("lzop", &["lzop:lzop"]),
	("hdparm", &["hdparm_project:hdparm"]),
	("lsof", &["lsof_project:lsof"]),
	("ntpclient", &["ntpclient_project:ntpclient"]),
	("pptpd", &["poptop:pptpd"]),
];

/// A file named libc.so could be musl, uClibc or glibc. Filename cannot tell them apart;
/// content can, and getting it wrong changes the CVE identity entirely.
pub const LIBC_MARKER: &[(&str, &str)] = &[
	("musl libc", "musl"),
	("uClibc", "uclibc"),
	("GNU C Library", "glibc"),
];
