[package]
name = "felf-unpack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
felf-core = { path = "../core" }
anyhow.workspace = true
thiserror.workspace = true
flate2.workspace = true
lzma-rs.workspace = true
