[package]
name = "felf-identify"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
felf-core = { path = "../core" }
anyhow.workspace = true
regex.workspace = true

[dev-dependencies]
felf-core = { path = "../core" }
